# -*- coding: utf-8 -*-
"""Bridgman Calculations Uncertainty Quantification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bh044X_P6iIN4UNPo9RmbNZfuef3jUX9
"""

import numpy as np
import pandas as pd



def running_average(file):
  running_ave = np.zeros([len(file.iloc[:,0]), len(file.iloc[0,:])])
  for i in range(len(file.iloc[0,:])):
    for j in range(len(file.iloc[:,0])):
      mov_average = file.iloc[0:j+1,i].mean() 
      running_ave[j,i] = mov_average
  return(running_ave)

def relative_abs_error(a,b):
  error = np.abs(a-b)
  rae = error/a
  return rae

def test_equilibration(running_average_data):  
  start_index_frac = 0.2
  test_index_array = np.arange(start_index_frac, 0.8001, 0.005)
  test_index = test_index_array*len(running_average_data)
  test_points_index = test_index.astype(int)
  
  equilibration_point = 0
  for i in range(len(test_points_index)):
    check_index = test_points_index[i]
    equilibration_point = check_index
    for j in range(len(running_average_data[0,:])):
      check_range = np.arange(0, 1999.01, 1) # test for 2 ns
      check_range = check_range.astype(int)
      for k in check_range:
        if relative_abs_error(running_average_data[check_index,j], running_average_data[(check_index+k),j]) > 0.002: # tolerance 2e-3
          break
      else:
        continue
      break
    else:
      break
  return equilibration_point, test_points_index

def swap_columns(df, col1, col2):
    col_list = list(df.columns)
    x, y = col_list.index(col1), col_list.index(col2)
    col_list[y], col_list[x] = col_list[x], col_list[y]
    df = df[col_list]
    return df

def running_average_array(array):
  running_ave = np.zeros([len(array)])
  for i in range(len(array)):
    mov_average = np.mean(array[0:i+1])
    running_ave[i] = mov_average
  return(running_ave)

Bridgman_Output_data = pd.read_table("Output_INDEX1_NPT.txt", sep='\s+')

Bridgman_Output_data = swap_columns(Bridgman_Output_data, 'P', 'V')

run_ave_Bridgman_data = running_average(Bridgman_Output_data.iloc[:,:])

equilibration_start = test_equilibration(run_ave_Bridgman_data[:,2:5])

#print(equilibration_start[0])

equilibration_time_index = equilibration_start[0]
rem = equilibration_time_index%100 # to find equib time to the nearest 100 ps

to_add = 0


if rem != 0:
  to_add = 100 - rem

final_equib_time = equilibration_time_index + to_add

final_equib_time = int(final_equib_time)

final_equib_time_stored = np.array([final_equib_time])*1000

np.savetxt('final_equib_time_INDEX1.txt', final_equib_time_stored)

Bridgman_equib_data = running_average(Bridgman_Output_data.iloc[final_equib_time:,:])

ave_density = Bridgman_equib_data[-1,2]
ave_density = np.array([ave_density])
np.savetxt('ave_density_INDEX1.txt', ave_density)


ave_Vol = Bridgman_equib_data[-1,4]
ave_Vol = np.array([ave_Vol])
np.savetxt('ave_Vol_INDEX1.txt', ave_Vol)


