# -*- coding: utf-8 -*-
"""Thermal_sim_extract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ECxVJ3vtlg3GffZJXqNPq2cDsJ5mw-3u
"""

import numpy as np
import pandas as pd

#DIR_INDEX_reshape_HFD

# >>>>>>>>>>>>>>>>>> computed par atom temp profile <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

temp_profile = pd.read_csv("temp_profile.DIR_INDEX_reshape_HFD.0.003", header=None)
temp_profile = temp_profile.iloc[3:,-1]
temp_profile_numpy = np.array(temp_profile)

num_heat_layers = 20
num_columns = int(num_heat_layers + 1)
num_rows = int(len(temp_profile_numpy)/num_columns)

temp_profile_numpy_split = np.array_split(temp_profile_numpy, num_rows)
temp_profile_numpy_reshaped = np.hstack(temp_profile_numpy_split).reshape((num_rows, num_columns))
temp_profile_numpy_reshaped = temp_profile_numpy_reshaped[:,1:].flatten()

split_temp_profile = np.array([line.split() for line in temp_profile_numpy_reshaped])
temp_profile_df = pd.DataFrame(split_temp_profile)
temp_profile_df = temp_profile_df.astype(float)

extracted_temp_profile = temp_profile_df.iloc[:,-1]
extracted_temp_profile = np.array(extracted_temp_profile)

np.savetxt("ext_final_temp_profile_DIR_INDEX_thermalcond.txt", extracted_temp_profile)



# >>>>>>>>>>>>>>>>>> lammps temp profile <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

temp_profile = pd.read_csv("lammps_temp_profile.DIR_INDEX_reshape_HFD.0.003", header=None)
temp_profile = temp_profile.iloc[3:,-1]
temp_profile_numpy = np.array(temp_profile)

num_heat_layers = 20
num_columns = int(num_heat_layers + 1)
num_rows = int(len(temp_profile_numpy)/num_columns)

temp_profile_numpy_split = np.array_split(temp_profile_numpy, num_rows)
temp_profile_numpy_reshaped = np.hstack(temp_profile_numpy_split).reshape((num_rows, num_columns))
temp_profile_numpy_reshaped = temp_profile_numpy_reshaped[:,1:].flatten()

split_temp_profile = np.array([line.split() for line in temp_profile_numpy_reshaped])
temp_profile_df = pd.DataFrame(split_temp_profile)
temp_profile_df = temp_profile_df.astype(float)

extracted_temp_profile = temp_profile_df.iloc[:,-1]
extracted_temp_profile = np.array(extracted_temp_profile)

np.savetxt("ext_final_lammps_temp_profile_DIR_INDEX_thermalcond.txt", extracted_temp_profile)



# >>>>>>>>>>>>>>>>>> mass density profile <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

massdens_profile = pd.read_csv("massdens_profile.DIR_INDEX_reshape_HFD.0.003", header=None)
massdens_profile = massdens_profile.iloc[3:,-1]
massdens_profile_numpy = np.array(massdens_profile)

num_heat_layers = 20
num_columns = int(num_heat_layers + 1)
num_rows = int(len(massdens_profile_numpy)/num_columns)

massdens_profile_numpy_split = np.array_split(massdens_profile_numpy, num_rows)
massdens_profile_numpy_reshaped = np.hstack(massdens_profile_numpy_split).reshape((num_rows, num_columns))
massdens_profile_numpy_reshaped = massdens_profile_numpy_reshaped[:,1:].flatten()

split_massdens_profile = np.array([line.split() for line in massdens_profile_numpy_reshaped])
massdens_profile_df = pd.DataFrame(split_massdens_profile)
massdens_profile_df = massdens_profile_df.astype(float)

extracted_massdens_profile = massdens_profile_df.iloc[:,-1]
extracted_massdens_profile = np.array(extracted_massdens_profile)

np.savetxt("ext_final_mass_density_profile_DIR_INDEX_thermalcond.txt", extracted_massdens_profile)



# >>>>>>>>>>>>>>>>>> number density profile <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

numdens_profile = pd.read_csv("numdens_profile.DIR_INDEX_reshape_HFD.0.003", header=None)
numdens_profile = numdens_profile.iloc[3:,-1]
numdens_profile_numpy = np.array(numdens_profile)

num_heat_layers = 20
num_columns = int(num_heat_layers + 1)
num_rows = int(len(numdens_profile_numpy)/num_columns)

numdens_profile_numpy_split = np.array_split(numdens_profile_numpy, num_rows)
numdens_profile_numpy_reshaped = np.hstack(numdens_profile_numpy_split).reshape((num_rows, num_columns))
numdens_profile_numpy_reshaped = numdens_profile_numpy_reshaped[:,1:].flatten()

split_numdens_profile = np.array([line.split() for line in numdens_profile_numpy_reshaped])
numdens_profile_df = pd.DataFrame(split_numdens_profile)
numdens_profile_df = numdens_profile_df.astype(float)

extracted_numdens_profile = numdens_profile_df.iloc[:,-1]
extracted_numdens_profile = np.array(extracted_numdens_profile)

np.savetxt("ext_final_number_density_profile_DIR_INDEX_thermalcond.txt", extracted_numdens_profile)




